"""Add superset fields to Exercise and TemplateExercise

Revision ID: a1c2a64860b4
Revises: 005_add_template_color
Create Date: 2026-01-29 18:43:45.527702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1c2a64860b4'
down_revision = '005_add_template_color'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_superset', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('superset_exercise_name', sa.String(length=100), nullable=True))

    with op.batch_alter_table('template_exercise', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_superset', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('superset_exercise_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_exercise', schema=None) as batch_op:
        batch_op.drop_column('superset_exercise_name')
        batch_op.drop_column('is_superset')

    with op.batch_alter_table('exercise', schema=None) as batch_op:
        batch_op.drop_column('superset_exercise_name')
        batch_op.drop_column('is_superset')

    # ### end Alembic commands ###
